language: node_js

sudo: required

dist: xenial

node_js: stable

branches:
  only:
    - starunner

before_install: 
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo generate
  - hexo deploy
