#
## Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CloudPool浊池
subtitle: 好像会一点了
description: 垃圾站点2
summary: CloudPool浊池是由一群年轻人管理的博客，它的初衷并不是要做一个高大上的博客，而是希望人们玩农药玩累了看段子看睡了无聊到搞Gay了的时候能看见有一些人在做一些让人看了暂时舒服一下的东西，说白了你可以把它理解为一个没那么吵的QQ空间。
mainauthor: StʌrunneR
github_username: cloudpool2017
language: zh-Hans
timezone: Asia/Chongqing
logo: /images/logo.png
favicon: /images/cloudpool-favicon.ico
keyword: 浊池, cloudpool

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zhuochi.org
# url: https://cloudpool.co
root: /
permalink: :title/
permalink_defaults:

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  ## repo: git@git.coding.net:CloudPool/CloudPool.git
  ## repo: git@gitlab.com:cloudpool2017/cloudpool-website.git
  ## branch: master

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
mag_dir: cloudpool
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date
  
# Category & Tag
default_category: 浊池
category_map:
  浊池: main
  浊诗: poem
  浊shi: sh*t 
  浊故事: story 
  浊技术: tec
  浊喳喳: zhazha
  浊物理: phys
  浊行: travel
  浊安利: anli
  浊拍: shooting 
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: vexo

about: 
  banner: /images/about.jpg
  avatar: /images/logo.png
  cloudpool: /images/cloudpool.png 
  sitedescription: CloudPool浊池是由一群年轻人管理的博客，目前托管于Github，文章、图片等来源于朋友们自愿提交。如果你也有兴趣加入我们或者给我们提意见，欢迎联系我们<br/><i>我们都是年轻人&emsp;&emsp;&emsp;&emsp;——乌青</i><br/><br/>
                   邮箱：（团队）cloudpool2017@gmail.com　（个人）lyj361@163.com<br/>
                   QQ：（团队）3379609674　（个人）1783074382<br />
  
member:
  total: 15
  m1: StʌrunneR
  descriptionm1: 站长
  contactm1: QQ 1783074382<br/>邮箱 lyj361@163.com
  m2: Dark.∞
  descriptionm2: 这个人什么都不想写，很懒
  contactm2: QQ 1287008710
  m3: Gunsbrook
  descriptionm3: 
  contactm3: QQ 1291183647<br/>1291183647@qq.com<br/>Gunsbrook Co.,Ltd.<br/>
  m4: Ghost
  descriptionm4:
  contactm4: QQ 970246988
  m5: 假面自白
  descriptionm5:
  contactm5:
  m6: 乡琳
  descriptionm6:
  contactm6:
  m7: 缀理
  descriptionm7:
  contactm7:
  m8: 稳稳
  descriptionm8:
  contactm8:
  m9: 林萌小公主
  descriptionm9:
  contactm9:
  m10: Rev.
  descriptionm10: 优雅
  contactm10:
  m11: Ripper 
  descriptionm11: 
  contactm11:
  m12: Cwtch💕
  descriptionm12: 
  contactm12:
  m13: 异类_Yasmine
  descriptionm13: 
  contactm13:
  m14: 熊率且比
  descriptionm14: 
  contactm14:
  m15: Salome
  descriptionm15: 
  contactm15:

  
# Lazyload
lazyload:
  enable: false
  onlypost: false
  loadingImg: #eg. ./images/loading.png
  
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: ./node_modules/hexo-helper-live2d/
  pluginJsPath: ./node_modules/hexo-helper-live2d/src/lib/
  pluginModelPath: ./node_modules/assets/
  model:
    use: live2d-widget-model-hijiki
    hHeadPos: 0.5
    vHeadPos: 0.3
  display:
    width: 100
    height: 200
    position: left
    hOffset: 0
    vOffset: -105
  mobile:
    show: false
  react:
    opacityDefault: 1.0
    opacityOnHover: 0.2
